# Generated by Django 4.2.2 on 2023-07-05 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ilock', '0003_task_remove_customuser_groups_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='task',
            field=models.TextField(default='', max_length=50, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='task',
            name='title',
            field=models.CharField(max_length=50, verbose_name='Название'),
        ),
    ]
